[package]
name = "fsym-core"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
fsym-budget.workspace = true
fsym-id.workspace = true
fsym-outcome.workspace = true
num-bigint.workspace = true
num-rational.workspace = true
num-traits.workspace = true
num-complex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
