[package]
name = "fsym-assumptions"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
fsym-core.workspace = true
fsym-id.workspace = true
fsym-logic.workspace = true
blake3.workspace = true
num-bigint.workspace = true
num-rational.workspace = true
num-traits.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
