"""Matrices module for FrankenSymPy (WS05, WS10)."""

from .dense import (
    DenseMatrix,
    GramSchmidt,
    ImmutableDenseMatrix,
    ImmutableMatrix,
    Matrix,
    MatrixBase,
    MutableDenseMatrix,
    casoratian,
    det,
    diag,
    eye,
    hadamard_product,
    hstack,
    jacobian,
    jordan_block,
    jordan_cell,
    kronecker_product,
    matrix_multiply_elementwise,
    ones,
    pinv,
    randMatrix,
    rank,
    shape,
    trace,
    vstack,
    wronskian,
    zeros,
)
from .sparse import (
    MutableSparseMatrix,
    SparseMatrix,
)

__all__ = [
    "DenseMatrix",
    "GramSchmidt",
    "ImmutableDenseMatrix",
    "ImmutableMatrix",
    "Matrix",
    "MatrixBase",
    "MutableDenseMatrix",
    "MutableSparseMatrix",
    "SparseMatrix",
    "casoratian",
    "det",
    "diag",
    "eye",
    "hadamard_product",
    "hstack",
    "jacobian",
    "jordan_block",
    "jordan_cell",
    "kronecker_product",
    "matrix_multiply_elementwise",
    "ones",
    "pinv",
    "randMatrix",
    "rank",
    "shape",
    "trace",
    "vstack",
    "wronskian",
    "zeros",
]
