[package]
name = "fsym-rational"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
fsym-bigint.workspace = true
fsym-budget.workspace = true
fsym-modular.workspace = true
num-rational = { workspace = true, features = ["serde"] }
num-traits.workspace = true
serde.workspace = true

[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true
