[package]
name = "fsym-modular"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
fsym-bigint.workspace = true
fsym-budget.workspace = true

[dev-dependencies]
proptest.workspace = true
