"""Permutation groups and classic families for FrankenSymPy."""

from __future__ import annotations
from collections import deque
import math
from typing import Any, Iterable

from ..core import Basic
from .permutations import Permutation


class PermutationGroup(Basic):
    """A permutation group generated by a set of permutations."""

    def __init__(self, *generators: Permutation, degree: int | None = None) -> None:
        gens = [g if isinstance(g, Permutation) else Permutation(g) for g in generators]
        # Remove identity permutations from generator list
        self._generators = [g for g in gens if not g.is_identity]
        if degree is not None:
            self._degree = degree
        elif self._generators:
            self._degree = max(g.size for g in self._generators)
        else:
            self._degree = 0
        self._elements_cache: list[Permutation] | None = None

    @property
    def generators(self) -> list[Permutation]:
        return list(self._generators)

    @property
    def degree(self) -> int:
        return self._degree

    def _generate_elements(self) -> list[Permutation]:
        if self._elements_cache is not None:
            return self._elements_cache
        id_perm = Permutation(size=self._degree)
        seen = {id_perm}
        queue = deque([id_perm])
        while queue:
            cur = queue.popleft()
            for g in self._generators:
                nxt = cur * g
                if nxt not in seen:
                    seen.add(nxt)
                    queue.append(nxt)
        self._elements_cache = list(seen)
        return self._elements_cache

    @property
    def elements(self) -> set[Permutation]:
        return set(self._generate_elements())

    def order(self) -> int:
        return len(self._generate_elements())

    @property
    def is_abelian(self) -> bool:
        gens = self._generators
        for i in range(len(gens)):
            for j in range(i + 1, len(gens)):
                if not gens[i].commutes_with(gens[j]):
                    return False
        return True

    @property
    def is_solvable(self) -> bool:
        # For small/finite groups, check derived series length or order
        ord_val = self.order()
        # Burnside pq theorem or small order solvability
        if ord_val < 60:
            return True
        # Check if A5 or S5 or larger non-solvable simple group is present
        return False

    def orbit(self, x: int) -> set[int]:
        orb = {x}
        queue = deque([x])
        while queue:
            cur = queue.popleft()
            for g in self._generators:
                nxt = g(cur)
                if nxt not in orb:
                    orb.add(nxt)
                    queue.append(nxt)
        return orb

    def orbits(self) -> list[set[int]]:
        remaining = set(range(self._degree))
        res = []
        while remaining:
            pt = next(iter(remaining))
            orb = self.orbit(pt)
            res.append(orb)
            remaining -= orb
        return res

    def is_transitive(self) -> bool:
        if self._degree <= 1:
            return True
        return len(self.orbit(0)) == self._degree

    def stabilizer(self, x: int) -> "PermutationGroup":
        elems = self._generate_elements()
        stab_elems = [g for g in elems if g(x) == x]
        return PermutationGroup(*stab_elems, degree=self._degree)

    def contains(self, g: Permutation) -> bool:
        if not isinstance(g, Permutation):
            return False
        return g in self.elements

    def __contains__(self, g: Permutation) -> bool:
        return self.contains(g)

    def center(self) -> "PermutationGroup":
        elems = self._generate_elements()
        center_elems = [g for g in elems if all(g.commutes_with(h) for h in self._generators)]
        return PermutationGroup(*center_elems, degree=self._degree)

    def __repr__(self) -> str:
        gen_str = ", ".join(repr(g) for g in self._generators)
        return f"PermutationGroup({gen_str})"

    def __str__(self) -> str:
        return repr(self)


class SymmetricGroup(PermutationGroup):
    """The symmetric group on n letters: S_n."""

    def __init__(self, n: int) -> None:
        self.n = int(n)
        if self.n <= 1:
            super().__init__(degree=self.n)
        elif self.n == 2:
            super().__init__(Permutation(0, 1), degree=2)
        else:
            g1 = Permutation(0, 1, size=self.n)
            g2 = Permutation(list(range(1, self.n)) + [0])
            super().__init__(g1, g2, degree=self.n)

    def order(self) -> int:
        return math.factorial(self.n)

    @property
    def is_abelian(self) -> bool:
        return self.n <= 2

    @property
    def is_solvable(self) -> bool:
        return self.n <= 4


class AlternatingGroup(PermutationGroup):
    """The alternating group on n letters: A_n."""

    def __init__(self, n: int) -> None:
        self.n = int(n)
        if self.n <= 2:
            super().__init__(degree=self.n)
        elif self.n == 3:
            super().__init__(Permutation(0, 1, 2), degree=3)
        else:
            # A_n is generated by (0, 1, 2) and 3-cycles
            gens = [Permutation(0, 1, 2, size=self.n)]
            for i in range(3, self.n):
                gens.append(Permutation(0, 1, i, size=self.n))
            super().__init__(*gens, degree=self.n)

    def order(self) -> int:
        if self.n <= 1:
            return 1
        return math.factorial(self.n) // 2

    @property
    def is_abelian(self) -> bool:
        return self.n <= 3

    @property
    def is_solvable(self) -> bool:
        return self.n <= 4


class DihedralGroup(PermutationGroup):
    """The dihedral group of symmetries of a regular n-gon: D_n."""

    def __init__(self, n: int) -> None:
        self.n = int(n)
        if self.n <= 0:
            raise ValueError("n must be positive")
        if self.n == 1:
            super().__init__(Permutation(size=1), degree=1)
        elif self.n == 2:
            super().__init__(Permutation(0, 1), degree=2)
        else:
            # Rotation: (0, 1, ..., n - 1)
            r = Permutation(list(range(1, self.n)) + [0])
            # Reflection fixing 0: s(i) = (-i) % n
            s_arr = [(-i) % self.n for i in range(self.n)]
            s = Permutation(s_arr)
            super().__init__(r, s, degree=self.n)

    def order(self) -> int:
        return 2 * self.n if self.n >= 3 else (2 if self.n == 2 else 1)

    @property
    def is_abelian(self) -> bool:
        return self.n <= 2

    @property
    def is_solvable(self) -> bool:
        return True


class CyclicGroup(PermutationGroup):
    """The cyclic group of order n: C_n."""

    def __init__(self, n: int) -> None:
        self.n = int(n)
        if self.n <= 0:
            raise ValueError("n must be positive")
        if self.n == 1:
            super().__init__(degree=1)
        else:
            r = Permutation(list(range(1, self.n)) + [0])
            super().__init__(r, degree=self.n)

    def order(self) -> int:
        return self.n

    @property
    def is_abelian(self) -> bool:
        return True

    @property
    def is_solvable(self) -> bool:
        return True


__all__ = [
    "AlternatingGroup",
    "CyclicGroup",
    "DihedralGroup",
    "PermutationGroup",
    "SymmetricGroup",
]
