//! Candidate and Verified namespace separation (WS06).
//!
//! Layer: L2 (evidence namespaces).
//! Unverified candidates produced by generators are held in `CandidateNamespace` and
//! cannot enter `VerifiedNamespace` or be cached as accepted values without an
//! independent verification receipt.

#![forbid(unsafe_code)]

use crate::envelope::EvidenceEnvelope;
use crate::receipt::VerificationReceipt;
use fsym_assumptions::ImmutableAssumptionsSnapshot;
use fsym_outcome::EvidenceClass;
use fsym_proof_kernel::{Claim, verify_derivation_independent};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::collections::HashMap;
use thiserror::Error;

#[derive(Debug, Error, PartialEq, Eq)]
pub enum NamespaceError {
    #[error("Candidate not verified: receipt is missing or invalid")]
    UnverifiedCandidate,
    #[error("Receipt claim digest mismatch: receipt is not for this candidate")]
    ReceiptMismatch,
    #[error("Candidate not found in candidate namespace")]
    CandidateNotFound,
    #[error("Independent verification rejected the evidence: {0}")]
    IndependentVerificationFailed(String),
}

/// Unverified candidate term/claim namespace.
#[derive(Debug, Clone, Default)]
pub struct CandidateNamespace {
    candidates: HashMap<[u8; 32], Claim>,
}

#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct CandidateNamespaceWire {
    schema_version: u32,
    candidates: Vec<Claim>,
}

impl Serialize for CandidateNamespace {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut candidates: Vec<Claim> = self.candidates.values().cloned().collect();
        candidates.sort_by_key(Claim::digest);
        CandidateNamespaceWire {
            schema_version: 1,
            candidates,
        }
        .serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for CandidateNamespace {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let wire = CandidateNamespaceWire::deserialize(deserializer)?;
        if wire.schema_version != 1 {
            return Err(serde::de::Error::custom(format!(
                "unsupported candidate namespace schema version {}",
                wire.schema_version
            )));
        }
        let mut candidates = HashMap::with_capacity(wire.candidates.len());
        for claim in wire.candidates {
            let digest = claim.digest();
            if candidates.insert(digest, claim).is_some() {
                return Err(serde::de::Error::custom(
                    "duplicate candidate claim in namespace",
                ));
            }
        }
        Ok(Self { candidates })
    }
}

impl CandidateNamespace {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a candidate proposal generated by a heuristic/optimizing search.
    pub fn register_candidate(&mut self, claim: Claim) -> [u8; 32] {
        let digest = claim.digest();
        self.candidates.insert(digest, claim);
        digest
    }

    /// Retrieve a candidate by its content digest.
    pub fn get_candidate(&self, digest: &[u8; 32]) -> Option<&Claim> {
        self.candidates.get(digest)
    }

    /// Total number of pending candidates.
    pub fn count(&self) -> usize {
        self.candidates.len()
    }
}

/// A verified envelope bound to the exact assumptions snapshot used for replay.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct VerifiedEvidence {
    pub envelope: EvidenceEnvelope,
    pub context_digest: [u8; 32],
}

/// Verified term/claim namespace containing only independently replayed results.
///
/// This type intentionally does not implement `Deserialize`: imported envelopes must
/// cross [`Self::insert_verified`] with an explicit assumptions snapshot instead of
/// materializing accepted state around the verifier.
#[derive(Debug, Clone, Default)]
pub struct VerifiedNamespace {
    verified: HashMap<[u8; 32], VerifiedEvidence>,
}

#[derive(Serialize)]
struct VerifiedNamespaceWire<'a> {
    schema_version: u32,
    verified: Vec<&'a VerifiedEvidence>,
}

impl Serialize for VerifiedNamespace {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut verified: Vec<&VerifiedEvidence> = self.verified.values().collect();
        verified.sort_by_key(|evidence| evidence.envelope.claim.digest());
        VerifiedNamespaceWire {
            schema_version: 1,
            verified,
        }
        .serialize(serializer)
    }
}

impl VerifiedNamespace {
    pub fn new() -> Self {
        Self::default()
    }

    /// Promote a candidate from `CandidateNamespace` into `VerifiedNamespace`
    /// by presenting a valid verification receipt.
    pub fn promote_candidate(
        &mut self,
        candidate_digest: &[u8; 32],
        candidates: &mut CandidateNamespace,
        receipt: VerificationReceipt,
        derivation: Option<fsym_proof_kernel::DerivationTree>,
        context: &ImmutableAssumptionsSnapshot,
    ) -> Result<VerifiedEvidence, NamespaceError> {
        let claim = candidates
            .candidates
            .get(candidate_digest)
            .cloned()
            .ok_or(NamespaceError::CandidateNotFound)?;

        if receipt.claim_digest != claim.digest() {
            return Err(NamespaceError::ReceiptMismatch);
        }

        let envelope = EvidenceEnvelope::new(claim, receipt.evidence_class, receipt, derivation);
        let verified = independently_verify_envelope(envelope, context)?;

        candidates.candidates.remove(candidate_digest);
        self.verified.insert(*candidate_digest, verified.clone());
        Ok(verified)
    }

    /// Directly insert an externally verified evidence envelope.
    pub fn insert_verified(
        &mut self,
        envelope: EvidenceEnvelope,
        context: &ImmutableAssumptionsSnapshot,
    ) -> Result<(), NamespaceError> {
        let claim_digest = envelope.claim.digest();
        let verified = independently_verify_envelope(envelope, context)?;
        self.verified.insert(claim_digest, verified);
        Ok(())
    }

    /// Retrieve a verified evidence envelope by claim digest.
    pub fn get_verified(&self, claim_digest: &[u8; 32]) -> Option<&VerifiedEvidence> {
        self.verified.get(claim_digest)
    }

    /// Total number of certified claims in this namespace.
    pub fn count(&self) -> usize {
        self.verified.len()
    }
}

fn independently_verify_envelope(
    envelope: EvidenceEnvelope,
    context: &ImmutableAssumptionsSnapshot,
) -> Result<VerifiedEvidence, NamespaceError> {
    if envelope.evidence_class != EvidenceClass::KernelProved {
        return Err(NamespaceError::IndependentVerificationFailed(format!(
            "evidence class `{}` has no live trusted verifier",
            envelope.evidence_class.as_str()
        )));
    }
    if !envelope.verify_integrity() {
        return Err(NamespaceError::UnverifiedCandidate);
    }
    let derivation = envelope
        .derivation
        .as_ref()
        .ok_or(NamespaceError::UnverifiedCandidate)?;
    let verified_claim = verify_derivation_independent(derivation, context)
        .map_err(|error| NamespaceError::IndependentVerificationFailed(error.to_string()))?;
    if verified_claim != envelope.claim {
        return Err(NamespaceError::IndependentVerificationFailed(
            "verified derivation root does not match the envelope claim".to_string(),
        ));
    }
    Ok(VerifiedEvidence {
        envelope,
        context_digest: context.digest(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use fsym_core::Expr;
    use fsym_id::ReceiptId;
    use fsym_outcome::EvidenceClass;
    use fsym_proof_kernel::{Claim, DerivationStep, DerivationTree, ProofRule, StepId};

    #[test]
    fn promotion_requires_matching_receipt_and_integrity() {
        let mut candidates = CandidateNamespace::new();
        let mut verified = VerifiedNamespace::new();
        let ctx = ImmutableAssumptionsSnapshot::empty();

        let claim = Claim::equality(Expr::symbol("x"), Expr::symbol("x"));
        let digest = candidates.register_candidate(claim.clone());
        assert_eq!(candidates.count(), 1);
        assert_eq!(verified.count(), 0);

        let derivation = DerivationTree {
            steps: vec![DerivationStep {
                id: StepId(0),
                rule: ProofRule::Reflexivity(Expr::symbol("x")),
                claim: claim.clone(),
            }],
            root: StepId(0),
        };

        // Valid receipt bound to the derivation root and digest.
        let receipt = VerificationReceipt::issue(
            ReceiptId::new(1).unwrap(),
            &claim,
            EvidenceClass::KernelProved,
            "fsym-proof-kernel",
            100,
            Some(derivation.digest()),
        );

        let envelope = verified
            .promote_candidate(&digest, &mut candidates, receipt, Some(derivation), &ctx)
            .expect("promotion succeeds");

        assert_eq!(candidates.count(), 0);
        assert_eq!(verified.count(), 1);
        assert!(envelope.envelope.verify_integrity());
        assert_eq!(envelope.context_digest, ctx.digest());
    }

    #[test]
    fn promotion_with_mismatched_receipt_is_rejected() {
        let mut candidates = CandidateNamespace::new();
        let mut verified = VerifiedNamespace::new();
        let ctx = ImmutableAssumptionsSnapshot::empty();

        let claim_a = Claim::equality(Expr::symbol("x"), Expr::symbol("x"));
        let claim_b = Claim::equality(Expr::symbol("y"), Expr::symbol("y"));

        let digest_a = candidates.register_candidate(claim_a);

        // Receipt issued for claim_b instead of claim_a
        let wrong_receipt = VerificationReceipt::issue(
            ReceiptId::new(2).unwrap(),
            &claim_b,
            EvidenceClass::KernelProved,
            "fsym-proof-kernel",
            101,
            None,
        );

        let err = verified
            .promote_candidate(&digest_a, &mut candidates, wrong_receipt, None, &ctx)
            .unwrap_err();
        assert_eq!(err, NamespaceError::ReceiptMismatch);
        assert_eq!(candidates.count(), 1);
        assert_eq!(verified.count(), 0);
    }

    #[test]
    fn kernel_proved_promotion_without_derivation_is_rejected() {
        let mut candidates = CandidateNamespace::new();
        let mut verified = VerifiedNamespace::new();
        let ctx = ImmutableAssumptionsSnapshot::empty();
        let claim = Claim::equality(Expr::symbol("x"), Expr::symbol("x"));
        let digest = candidates.register_candidate(claim.clone());
        let receipt = VerificationReceipt::issue(
            ReceiptId::new(3).unwrap(),
            &claim,
            EvidenceClass::KernelProved,
            "forged-receipt-only-verifier",
            102,
            None,
        );

        let error = verified
            .promote_candidate(&digest, &mut candidates, receipt, None, &ctx)
            .unwrap_err();

        assert_eq!(error, NamespaceError::UnverifiedCandidate);
        assert_eq!(candidates.count(), 1);
        assert_eq!(verified.count(), 0);
    }

    #[test]
    fn kernel_proved_envelope_with_mismatched_derivation_root_is_rejected() {
        let mut verified = VerifiedNamespace::new();
        let ctx = ImmutableAssumptionsSnapshot::empty();
        let x = Expr::symbol("x");
        let published_claim = Claim::equality(x.clone(), Expr::symbol("y"));
        let derived_claim = Claim::equality(x.clone(), x.clone());
        let derivation = DerivationTree {
            steps: vec![DerivationStep {
                id: StepId(0),
                rule: ProofRule::Reflexivity(x),
                claim: derived_claim,
            }],
            root: StepId(0),
        };
        let receipt = VerificationReceipt::issue(
            ReceiptId::new(4).unwrap(),
            &published_claim,
            EvidenceClass::KernelProved,
            "forged-claim-binding",
            103,
            Some(derivation.digest()),
        );
        let envelope = EvidenceEnvelope::new(
            published_claim,
            EvidenceClass::KernelProved,
            receipt,
            Some(derivation),
        );

        let error = verified.insert_verified(envelope, &ctx).unwrap_err();

        assert_eq!(error, NamespaceError::UnverifiedCandidate);
        assert_eq!(verified.count(), 0);
    }

    #[test]
    fn structurally_bound_but_invalid_derivation_is_rejected() {
        let mut verified = VerifiedNamespace::new();
        let ctx = ImmutableAssumptionsSnapshot::empty();
        let x = Expr::symbol("x");
        let forged_claim = Claim::equality(x.clone(), Expr::symbol("y"));
        let derivation = DerivationTree {
            steps: vec![DerivationStep {
                id: StepId(0),
                rule: ProofRule::Reflexivity(x),
                claim: forged_claim.clone(),
            }],
            root: StepId(0),
        };
        let receipt = VerificationReceipt::issue(
            ReceiptId::new(5).unwrap(),
            &forged_claim,
            EvidenceClass::KernelProved,
            "untrusted-self-issued-receipt",
            104,
            Some(derivation.digest()),
        );
        let envelope = EvidenceEnvelope::new(
            forged_claim,
            EvidenceClass::KernelProved,
            receipt,
            Some(derivation),
        );
        assert!(envelope.verify_integrity());

        let error = verified.insert_verified(envelope, &ctx).unwrap_err();

        assert!(matches!(
            error,
            NamespaceError::IndependentVerificationFailed(_)
        ));
        assert_eq!(verified.count(), 0);
    }

    #[test]
    fn candidate_namespace_has_deterministic_json_roundtrip() {
        let mut first = CandidateNamespace::new();
        first.register_candidate(Claim::equality(Expr::symbol("z"), Expr::symbol("z")));
        first.register_candidate(Claim::equality(Expr::symbol("a"), Expr::symbol("a")));

        let json = serde_json::to_string(&first).expect("namespace has a JSON wire format");
        let restored: CandidateNamespace =
            serde_json::from_str(&json).expect("canonical namespace roundtrips");

        assert_eq!(restored.count(), first.count());
        assert_eq!(
            serde_json::to_string(&restored).unwrap(),
            json,
            "digest-index reconstruction must not perturb canonical ordering"
        );
    }

    #[test]
    fn candidate_namespace_rejects_duplicate_claims_on_import() {
        let claim = Claim::equality(Expr::symbol("x"), Expr::symbol("x"));
        let wire = serde_json::json!({
            "schema_version": 1,
            "candidates": [claim.clone(), claim],
        });

        assert!(serde_json::from_value::<CandidateNamespace>(wire).is_err());
    }

    #[test]
    fn verified_namespace_serializes_without_non_string_map_keys() {
        let mut verified = VerifiedNamespace::new();
        let ctx = ImmutableAssumptionsSnapshot::empty();
        let x = Expr::symbol("x");
        let claim = Claim::equality(x.clone(), x.clone());
        let derivation = DerivationTree {
            steps: vec![DerivationStep {
                id: StepId(0),
                rule: ProofRule::Reflexivity(x),
                claim: claim.clone(),
            }],
            root: StepId(0),
        };
        let receipt = VerificationReceipt::issue(
            ReceiptId::new(6).unwrap(),
            &claim,
            EvidenceClass::KernelProved,
            "test-verifier",
            105,
            Some(derivation.digest()),
        );
        verified
            .insert_verified(
                EvidenceEnvelope::new(
                    claim,
                    EvidenceClass::KernelProved,
                    receipt,
                    Some(derivation),
                ),
                &ctx,
            )
            .unwrap();

        let json = serde_json::to_string(&verified).expect("verified namespace is JSON encodable");
        assert!(json.contains("\"schema_version\":1"));
        assert!(json.contains("\"verified\":["));
    }
}
