//! Candidate and Verified namespace separation (WS06).
//!
//! Layer: L2 (evidence namespaces).
//! Unverified candidates produced by generators are held in `CandidateNamespace` and
//! cannot enter `VerifiedNamespace` or be cached as accepted values without an
//! independent verification receipt.

#![forbid(unsafe_code)]

use crate::envelope::EvidenceEnvelope;
use crate::receipt::VerificationReceipt;
use fsym_proof_kernel::Claim;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use thiserror::Error;

#[derive(Debug, Error, PartialEq, Eq)]
pub enum NamespaceError {
    #[error("Candidate not verified: receipt is missing or invalid")]
    UnverifiedCandidate,
    #[error("Receipt claim digest mismatch: receipt is not for this candidate")]
    ReceiptMismatch,
    #[error("Candidate not found in candidate namespace")]
    CandidateNotFound,
}

/// Unverified candidate term/claim namespace.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CandidateNamespace {
    candidates: HashMap<[u8; 32], Claim>,
}

impl CandidateNamespace {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a candidate proposal generated by a heuristic/optimizing search.
    pub fn register_candidate(&mut self, claim: Claim) -> [u8; 32] {
        let digest = claim.digest();
        self.candidates.insert(digest, claim);
        digest
    }

    /// Retrieve a candidate by its content digest.
    pub fn get_candidate(&self, digest: &[u8; 32]) -> Option<&Claim> {
        self.candidates.get(digest)
    }

    /// Total number of pending candidates.
    pub fn count(&self) -> usize {
        self.candidates.len()
    }
}

/// Verified term/claim namespace containing only certified results with receipts.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct VerifiedNamespace {
    verified: HashMap<[u8; 32], EvidenceEnvelope>,
}

impl VerifiedNamespace {
    pub fn new() -> Self {
        Self::default()
    }

    /// Promote a candidate from `CandidateNamespace` into `VerifiedNamespace`
    /// by presenting a valid verification receipt.
    pub fn promote_candidate(
        &mut self,
        candidate_digest: &[u8; 32],
        candidates: &mut CandidateNamespace,
        receipt: VerificationReceipt,
        derivation: Option<fsym_proof_kernel::DerivationTree>,
    ) -> Result<EvidenceEnvelope, NamespaceError> {
        let claim = candidates
            .candidates
            .remove(candidate_digest)
            .ok_or(NamespaceError::CandidateNotFound)?;

        if receipt.claim_digest != claim.digest() {
            return Err(NamespaceError::ReceiptMismatch);
        }

        let envelope = EvidenceEnvelope::new(claim, receipt.evidence_class, receipt, derivation);
        if !envelope.verify_integrity() {
            return Err(NamespaceError::UnverifiedCandidate);
        }

        self.verified.insert(*candidate_digest, envelope.clone());
        Ok(envelope)
    }

    /// Directly insert an externally verified evidence envelope.
    pub fn insert_verified(&mut self, envelope: EvidenceEnvelope) -> Result<(), NamespaceError> {
        if !envelope.verify_integrity() {
            return Err(NamespaceError::UnverifiedCandidate);
        }
        self.verified.insert(envelope.claim.digest(), envelope);
        Ok(())
    }

    /// Retrieve a verified evidence envelope by claim digest.
    pub fn get_verified(&self, claim_digest: &[u8; 32]) -> Option<&EvidenceEnvelope> {
        self.verified.get(claim_digest)
    }

    /// Total number of certified claims in this namespace.
    pub fn count(&self) -> usize {
        self.verified.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use fsym_core::Expr;
    use fsym_id::ReceiptId;
    use fsym_outcome::EvidenceClass;
    use fsym_proof_kernel::Claim;

    #[test]
    fn promotion_requires_matching_receipt_and_integrity() {
        let mut candidates = CandidateNamespace::new();
        let mut verified = VerifiedNamespace::new();

        let claim = Claim::equality(Expr::symbol("x"), Expr::symbol("x"));
        let digest = candidates.register_candidate(claim.clone());
        assert_eq!(candidates.count(), 1);
        assert_eq!(verified.count(), 0);

        // Valid receipt
        let receipt = VerificationReceipt::issue(
            ReceiptId::new(1).unwrap(),
            &claim,
            EvidenceClass::KernelProved,
            "fsym-proof-kernel",
            100,
            None,
        );

        let envelope = verified
            .promote_candidate(&digest, &mut candidates, receipt, None)
            .expect("promotion succeeds");

        assert_eq!(candidates.count(), 0);
        assert_eq!(verified.count(), 1);
        assert!(envelope.verify_integrity());
    }

    #[test]
    fn promotion_with_mismatched_receipt_is_rejected() {
        let mut candidates = CandidateNamespace::new();
        let mut verified = VerifiedNamespace::new();

        let claim_a = Claim::equality(Expr::symbol("x"), Expr::symbol("x"));
        let claim_b = Claim::equality(Expr::symbol("y"), Expr::symbol("y"));

        let digest_a = candidates.register_candidate(claim_a);

        // Receipt issued for claim_b instead of claim_a
        let wrong_receipt = VerificationReceipt::issue(
            ReceiptId::new(2).unwrap(),
            &claim_b,
            EvidenceClass::KernelProved,
            "fsym-proof-kernel",
            101,
            None,
        );

        let err = verified
            .promote_candidate(&digest_a, &mut candidates, wrong_receipt, None)
            .unwrap_err();
        assert_eq!(err, NamespaceError::ReceiptMismatch);
        assert_eq!(verified.count(), 0);
    }
}
