"""Logic and Boolean algebra submodule for FrankenSymPy."""

from __future__ import annotations

from .boolalg import (
    And,
    Boolean,
    BooleanAtom,
    BooleanFalse,
    BooleanFunction,
    BooleanTrue,
    Equivalent,
    ITE,
    Implies,
    NAND,
    NOR,
    Nand,
    Nor,
    Not,
    Or,
    POSform,
    SOPform,
    XNOR,
    Xnor,
    Xor,
    false,
    is_nnf,
    simplify_logic,
    to_cnf,
    to_dnf,
    to_nnf,
    true,
    truth_table,
)
from .inference import pl_true, satisfiable, valid

__all__ = [
    "And",
    "Boolean",
    "BooleanAtom",
    "BooleanFalse",
    "BooleanFunction",
    "BooleanTrue",
    "Equivalent",
    "ITE",
    "Implies",
    "NAND",
    "NOR",
    "Nand",
    "Nor",
    "Not",
    "Or",
    "POSform",
    "SOPform",
    "XNOR",
    "Xnor",
    "Xor",
    "false",
    "is_nnf",
    "pl_true",
    "satisfiable",
    "simplify_logic",
    "to_cnf",
    "to_dnf",
    "to_nnf",
    "true",
    "truth_table",
    "valid",
]
